const BASE = process.env.EXPO_PUBLIC_API_URL!;
export const endpoints = {
  incrementReligionPoints: `${BASE}/incrementReligionPoints`,
  awardPointsToUser: `${BASE}/awardPointsToUser`,
  completeChallenge: `${BASE}/completeChallenge`,
  createMultiDayChallenge: `${BASE}/createMultiDayChallenge`,
  completeChallengeDay: `${BASE}/completeChallengeDay`,
  generateChallenge: `${BASE}/generateChallenge`,
  generateDailyChallenge: `${BASE}/generateDailyChallenge`,
  skipDailyChallenge: `${BASE}/skipDailyChallenge`,
  askGeminiSimple: `${BASE}/askGeminiSimple`,
  confessionalAI: `${BASE}/confessionalAI`,
  askGeminiV2: `${BASE}/askGeminiV2`,
  updateStreakAndXP: `${BASE}/updateStreakAndXP`,
  getUserProfile: `${BASE}/getUserProfile`,
  seedFirestore: `${BASE}/seedFirestore`,
  backfillUserProfiles: `${BASE}/backfillUserProfiles`,
  updateUserProfileCallable: `${BASE}/updateUserProfileCallable`,
  completeSignupAndProfile: `${BASE}/completeSignupAndProfile`,
  startSubscriptionCheckout: `${BASE}/startSubscriptionCheckout`,
  startOneTimeTokenCheckout: `${BASE}/startOneTimeTokenCheckout`,
  startTokenCheckout: `${BASE}/startTokenCheckout`,
  createCheckoutSession: `${BASE}/createCheckoutSession`,
  createStripeSubscriptionIntent: `${BASE}/createStripeSubscriptionIntent`,
  startDonationCheckout: `${BASE}/startDonationCheckout`,
  startCheckoutSession: `${BASE}/startCheckoutSession`,
  createStripeCheckout: `${BASE}/createStripeCheckout`,
  createStripeSetupIntent: `${BASE}/createStripeSetupIntent`,
  finalizePaymentIntent: `${BASE}/finalizePaymentIntent`,
  createTokenPurchaseSheet: `${BASE}/createTokenPurchaseSheet`,
  createSubscriptionSession: `${BASE}/createSubscriptionSession`,
  onCompletedChallengeCreate: `${BASE}/onCompletedChallengeCreate`,
  handleStripeWebhookV2: `${BASE}/handleStripeWebhookV2`,
  cleanLegacySubscriptionFields: `${BASE}/cleanLegacySubscriptionFields`,
} as const;
