const BASE = process.env.EXPO_PUBLIC_API_URL!;
export const endpoints = {
  incrementReligionPoints: `${BASE}/incrementReligionPoints`,
  awardPointsToUser: `${BASE}/awardPointsToUser`,
  completeChallenge: `${BASE}/completeChallenge`,
  createMultiDayChallenge: `${BASE}/createMultiDayChallenge`,
  completeChallengeDay: `${BASE}/completeChallengeDay`,
  generateChallenge: `${BASE}/generateChallenge`,
  generateDailyChallenge: `${BASE}/generateDailyChallenge`,
  skipDailyChallenge: `${BASE}/skipDailyChallenge`,
  askGeminiSimple: `${BASE}/askGeminiSimple`,
  confessionalAI: `${BASE}/confessionalAI`,
  askGeminiV2: `${BASE}/askGeminiV2`,
  updateStreakAndXP: `${BASE}/updateStreakAndXP`,
  getUserProfile: `${BASE}/getUserProfile`,
  seedFirestore: `${BASE}/seedFirestore`,
  backfillUserProfiles: `${BASE}/backfillUserProfiles`,
  updateUserProfileCallable: `${BASE}/updateUserProfileCallable`,
  completeSignupAndProfile: `${BASE}/completeSignupAndProfile`,
  onCompletedChallengeCreate: `${BASE}/onCompletedChallengeCreate`,
  cleanLegacySubscriptionFields: `${BASE}/cleanLegacySubscriptionFields`,
} as const;
